# replace default config

# multipass: true
# full: true

plugins:

  # - name
  #
  # or:
  # - name: false
  # - name: true
  #
  # or:
  # - name:
  #     param1: 1
  #     param2: 2

  - removeDoctype: false
  - removeXMLProcInst: false
  - removeComments: false
  - removeMetadata: false
  - removeXMLNS: false
  - removeEditorsNSData: false
  - cleanupAttrs: false
  - inlineStyles: false
  - minifyStyles: false
  - convertStyleToAttrs: false
  - cleanupIDs: false
  - prefixIds: false
  - removeRasterImages: false
  - removeUselessDefs: false
  - cleanupNumericValues: false
  - cleanupListOfValues: false
  - convertColors: false
  - removeUnknownsAndDefaults: false
  - removeNonInheritableGroupAttrs: false
  - removeUselessStrokeAndFill: false
  - removeViewBox: false
  - cleanupEnableBackground: false
  - removeHiddenElems: false
  - removeEmptyText: false
  - convertShapeToPath: false
  - moveElemsAttrsToGroup: false
  - moveGroupAttrsToElems: false
  - collapseGroups: false
  - convertPathData: false
  - convertTransform: false
  - removeEmptyAttrs: false
  - removeEmptyContainers: false
  - mergePaths: false
  - removeUnusedNS: false
  - sortAttrs: false
  - removeTitle: false
  - removeDesc: false
  - removeDimensions: false
  - removeAttrs: false
  - removeElementsByAttr: false
  - addClassesToSVGElement: false
  - removeStyleElement: false
  - removeScriptElement: false
  - addAttributesToSVGElement: false

# configure the indent (default 4 spaces) used by `--pretty` here:
#
# @see https://github.com/svg/svgo/blob/master/lib/svgo/js2svg.js#L6 for more config options
#
# js2svg:
#  pretty: true
#  indent: '  '
